#!/bin/sh
#
# @name Gazebo airship
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#

. ${R}etc/init.d/rc.airship_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=lta}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=airship}

# Simulation only: allow arming without a GCS connection
param set-default NAV_DLL_ACT 0

# Motor outputs to the gz motor plugins: channel 1 = starboard, 2 = port;
# output 0..1 maps to rotor velocity 0..300 rad/s (thrust 18*u^2 N).
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX1 300
param set-default SIM_GZ_EC_MAX2 300

# Tilt pods on servo outputs 1 (starboard) and 2 (port); -1..1 spans
# -180..+180 deg (0 = forward, +0.5 = up). Placeholder range pending the
# vehicle specification.
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_MINA1 -180
param set-default SIM_GZ_SV_MAXA1 180
param set-default SIM_GZ_SV_MINA2 -180
param set-default SIM_GZ_SV_MAXA2 180

# Fixed-tilt allocation: collective thrust = Fx, differential = yaw.
# Pitch and roll are passively stable (buoyancy righting) and not
# allocated; tilt allocation arrives with the vectoring effectiveness.
param set-default CA_AIRFRAME 9
param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PY 1.5
param set-default CA_ROTOR0_CT 18
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PY -1.5
param set-default CA_ROTOR1_CT 18
