#!/bin/sh
#
# @name Generic Airship (Independent Vectoring)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#
# @output Motor1 starboard pod motor
# @output Motor2 port pod motor
# @output Servo1 starboard pod tilt
# @output Servo2 port pod tilt
#

. ${R}etc/init.d/rc.airship_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=lta}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=airship_vectored_independent}

# Simulation only: allow arming without a GCS connection
param set-default NAV_DLL_ACT 0

# gz motors: 1 = starboard, 2 = port; output 0..1 = rotor speed 0..300 rad/s
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX1 300
param set-default SIM_GZ_EC_MAX2 300

# Tilt servos: 1 = starboard, 2 = port; the angle range is a placeholder
# pending the vehicle specification
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_MINA1 -180
param set-default SIM_GZ_SV_MAXA1 180
param set-default SIM_GZ_SV_MINA2 -180
param set-default SIM_GZ_SV_MAXA2 180

# Independently vectored side pods; full yaw commands the 0/180 deg couple
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 1
param set-default CA_AIRSHIP_TLMIN -180
param set-default CA_AIRSHIP_TLMAX 180
