#!/bin/sh
#
# @name Generic Airship (Added Mass, Hull Drag)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=airship_fixed_am_drag}

. ${R}etc/init.d-posix/airframes/2500_gz_airship_fixed
