#!/bin/sh
#
# @name Generic Airship (Independent Vectoring, Hull Aerodynamics)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=airship_vectored_independent_aero}

# The 2504 vehicle in a gz model that gives the hull quadratic drag and
# rotational damping. Same airframe, same control code, a damped plant: run
# both to see what the loop owes to the model and what to itself.

. ${R}etc/init.d-posix/airframes/2504_gz_airship_vectored_independent
