#!/bin/sh
#
# @name Cloudship (Added Mass)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=cloudship_am}

. ${R}etc/init.d-posix/airframes/2510_gz_cloudship
