#!/bin/sh
#
# @name Generic Airship (Independent Vectoring, Added Mass)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=airship_vectored_independent_am}

. ${R}etc/init.d-posix/airframes/2520_gz_airship_vectored_independent
