#!/bin/sh
#
# @name Generic Airship
# @type Airship
# @class Airship
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#
# @output Motor1 starboard thruster
# @output Motor2 port thruster
# @output Servo1 right elevator
# @output Servo2 left elevator
# @output Servo3 upper rudder
# @output Servo4 lower rudder
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# One collective thrust command; a zero tilt range allocates no tilt servos
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 0
param set-default CA_AIRSHIP_TLMIN 0
param set-default CA_AIRSHIP_TLMAX 0

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 3
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS1_TYPE 3
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS2_TYPE 4
param set-default CA_SV_CS2_TRQ_Y 0.5
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS3_TRQ_Y 0.5
