#!/bin/sh
#
# @name Generic Airship (Independent Vectoring)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#
# @output Motor1 starboard pod motor
# @output Motor2 port pod motor
# @output Servo1 starboard pod tilt
# @output Servo2 port pod tilt
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# Independently vectored side pods with a full 360 deg tilt range: set
# CA_AIRSHIP_TLMIN/TLMAX to the tilt angles at the servo end stops and
# CA_AIRSHIP_TLT_R to the servo slew rate of the vehicle
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 1
param set-default CA_AIRSHIP_TLMIN -180
param set-default CA_AIRSHIP_TLMAX 180
param set-default CA_AIRSHIP_TLT_R 120

# Set THR_MDL_FAC from the measured thrust curve. The AS_YAWRATE_* defaults
# come from the gz airship_vectored_independent model, which has no hull
# aerodynamics and no added mass, so its yaw plant has none of the damping a
# real hull has: retune them on the vehicle
