#!/bin/sh
#
# @name Cloudship
# @type Airship
# @class Airship
#
# @output Motor1 starboard thruster
# @output Motor2 port thruster
# @output Motor3 tail thruster
# @output Servo1 thrust tilt
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# One collective thrust and tilt command with a reversible tail yaw
# thruster. The symmetric range keeps level thrust at servo output 0,
# matching the original mixer calibration; the range and slew rate are
# placeholders pending vehicle data.
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 0
param set-default CA_AIRSHIP_TAIL 1
param set-default CA_AIRSHIP_TLMIN -90
param set-default CA_AIRSHIP_TLMAX 90
param set-default CA_AIRSHIP_TLT_R 120

param set-default CA_R_REV 4
