#!/bin/sh
#
# @name Cloudship
# @type Airship
# @class Airship
#
# @output Motor1 starboard thruster
# @output Motor2 port thruster
# @output Motor3 tail thruster
# @output Servo1 thrust tilt
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# One collective thrust and tilt command with a reversible tail yaw
# thruster; the tilt range is a placeholder pending vehicle data
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 0
param set-default CA_AIRSHIP_AUX 1
param set-default CA_AIRSHIP_TLMIN 0
param set-default CA_AIRSHIP_TLMAX 90

param set-default CA_R_REV 4
