#!/bin/sh
#
# @name Generic Airship (Independent Vectoring)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#
# @output Motor1 starboard pod motor
# @output Motor2 port pod motor
# @output Servo1 starboard pod tilt
# @output Servo2 port pod tilt
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# Independently vectored side pods with a full 360 deg tilt range: set
# CA_AIRSHIP_TLMIN/TLMAX to the tilt angles at the servo end stops and
# CA_AIRSHIP_TLT_R to the servo slew rate of the vehicle
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 1
param set-default CA_AIRSHIP_TLMIN -180
param set-default CA_AIRSHIP_TLMAX 180
param set-default CA_AIRSHIP_TLT_R 120

# Set THR_MDL_FAC from the measured thrust curve; the AS_YAWRATE_* defaults
# were tuned in the gz airship_vectored_independent model with THR_MDL_FAC 1,
# whose hull meets no air at all, before its tail was sized (yaw inertia
# 76.5 kg m^2 then, 108.8 now): retune them on the vehicle. The posix 2521 to
# 2527 plants add hull drag, fin lift and added mass, and the defaults were
# not retuned against any of them
