#!/bin/sh
#
# @name Generic Airship (Independent Vectoring)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#
# @output Motor1 starboard pod motor
# @output Motor2 port pod motor
# @output Servo1 starboard pod tilt
# @output Servo2 port pod tilt
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# Independently vectored side pods with a full 360 deg tilt range: set
# CA_AIRSHIP_TLMIN/TLMAX to the tilt angles at the servo end stops and
# CA_AIRSHIP_TLT_R to the servo slew rate of the vehicle
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 1
param set-default CA_AIRSHIP_TLMIN -180
param set-default CA_AIRSHIP_TLMAX 180
param set-default CA_AIRSHIP_TLT_R 120

# Set THR_MDL_FAC from the measured thrust curve; the AS_YAWRATE_* defaults
# were tuned in the gz airship_vectored_independent model with THR_MDL_FAC 1,
# on a hull that meets no air at all and had 79 kg m^2 of yaw inertia (129
# with the tail it now carries): retune them on the vehicle. The posix 2521
# to 2527 plants add hull drag, fin lift and added mass, the last of them
# 192 kg m^2 of yaw inertia on its own, and the defaults were not retuned
# against any of them
