#!/bin/sh
#
# @name Generic Airship (Independent Vectoring)
#
# @type Airship
# @class Airship
#
# @maintainer Hyunduk Shin <hyunduk@icarus-airship.com>
#
# @output Motor1 starboard pod motor
# @output Motor2 port pod motor
# @output Servo1 starboard pod tilt
# @output Servo2 port pod tilt
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2

# Independently vectored side pods with a full 360 deg tilt range: set
# CA_AIRSHIP_TLMIN/TLMAX to the tilt angles at the servo end stops and
# CA_AIRSHIP_TLT_R to the servo slew rate of the vehicle
param set-default CA_AIRFRAME 16
param set-default CA_AIRSHIP_GRP 1
param set-default CA_AIRSHIP_TLMIN -180
param set-default CA_AIRSHIP_TLMAX 180
param set-default CA_AIRSHIP_TLT_R 120

# Set THR_MDL_FAC from the measured thrust curve, then retune the AS_YAWRATE_*
# gains on the vehicle. The defaults were tuned in gz with THR_MDL_FAC 1, on
# this airframe's rigid, fin and complete plants (posix 2520, 2522, 2527) and
# the Cloudship's rigid and complete ones (2510, 2517). AS_YAWRATE_FF, the
# yaw torque per rad/s of setpoint that holds a turn against the hull's yaw
# damping, stays 0 here: posix 2522 and 2527 set theirs from their own
# damping, and the vehicle's has to be measured
